--Setting up Context

--create warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

--create database
CREATE OR REPLACE DATABASE RETAIL_DB;

--create schemas
CREATE OR REPLACE SCHEMA RETAIL_RAW;
CREATE OR REPLACE SCHEMA RETAIL_CORE;
CREATE OR REPLACE SCHEMA RETAIL_MART;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS;