--set context
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA RETAIL_RAW;

--create raw tables
CREATE OR REPLACE TABLE RAW_USERS(
    ID STRING,
    NAME STRING,
    EMAIL STRING,
    ROLE STRING,
    CREATED_AT DATE
);

CREATE OR REPLACE TABLE RAW_CUSTOMERS(
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CITY STRING,
    STATE STRING,
    CUSTOMER_TYPE STRING
);

CREATE OR REPLACE TABLE RAW_PRODUCTS(
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,
    UNIT_PRICE NUMBER,
    STOCK_QUANTITY INTEGER
);

CREATE OR REPLACE TABLE RAW_SALES_TRANSACTIONS(
    TRANSACTION_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY INTEGER,
    SALES_AMOUNT NUMBER,
    DISCOUNT_AMOUNT NUMBER,
    PROFIT_AMOUNT NUMBER,
    TRANSACTION_DATE DATE,
    PAYMENT_MODE STRING,
    BRANCH_LOCATION STRING
);

CREATE OR REPLACE TABLE RAW_FRAUD_SALES_ALERT(
    RAW_DATA VARIANT
);

SHOW TABLES;

--CREATE FILE FORMATS
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = JSON;

SHOW FILE FORMATS;

--CREATE STAGES
CREATE OR REPLACE STAGE RETAIL_CSV_STAGE
URL ='s3://snowflakebucket1329/'
CREDENTIALS =(
    AWS_KEY_ID=' '
    AWS_SECRET_KEY=' '
)
FILE_FORMAT =CSV_FORMAT ;

CREATE OR REPLACE STAGE RETAIL_JSON_STAGE
URL ='s3://krct-amazon-jasper-bucket/'
CREDENTIALS =(
    AWS_KEY_ID=' '
    AWS_SECRET_KEY=' '
)
FILE_FORMAT = JSON_FORMAT;

SHOW STAGES;

LIST @RETAIL_CSV_STAGE;
LIST @RETAIL_JSON_STAGE;


-- create pipes
CREATE OR REPLACE PIPE USER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_USERS
FROM @RETAIL_CSV_STAGE
PATTERN = '.*user.*[.]csv'
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE CUSTOMER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_CUSTOMERS
FROM @RETAIL_CSV_STAGE
PATTERN = '.*customer.*[.]csv'
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE PRODUCT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_PRODUCTS
FROM @RETAIL_CSV_STAGE
PATTERN = '.*product.*[.]csv'
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE SALES_TRANSACTION_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_SALES_TRANSACTIONS
FROM @RETAIL_CSV_STAGE
PATTERN = '.*transaction.*[.]csv'
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE FRAUD_SALES_ALERT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_FRAUD_SALES_ALERT
FROM @RETAIL_JSON_STAGE
PATTERN = '.*alert.*[.]json'
FILE_FORMAT = JSON_FORMAT;

SHOW PIPES;

SELECT * FROM RAW_USERS;
SELECT * FROM RAW_CUSTOMERS;
SELECT * FROM RAW_PRODUCTS;
SELECT * FROM RAW_SALES_TRANSACTIONS;
SELECT * FROM RAW_FRAUD_SALES_ALERT;


--Dynamic table to flatten json data
CREATE OR REPLACE DYNAMIC TABLE FLAT_FRAUD_SALES_ALERT
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT
    VALUE:ID::STRING AS ID,
    VALUE:TRANSACTION_ID::STRING AS TRANSACTION_ID,
    VALUE:REASON::STRING AS REASON,
    VALUE:FRAUD_SCORE::NUMBER AS FRAUD_SCORE,
    VALUE:STATUS::STRING AS STATUS
FROM RAW_FRAUD_SALES_ALERT,
LATERAL FLATTEN(INPUT => RAW_DATA);

SELECT * FROM FLAT_FRAUD_SALES_ALERT;