-- SET CONTEXT
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA RETAIL_RAW;

--CREATE STREAMS
CREATE OR REPLACE STREAM USER_STREAM
ON TABLE RAW_USERS;

CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE RAW_CUSTOMERS;

CREATE OR REPLACE STREAM PRODUCT_STREAM
ON TABLE RAW_PRODUCTS;

CREATE OR REPLACE STREAM SALES_TRANSACTION_STREAM
ON TABLE RAW_SALES_TRANSACTIONS;

CREATE OR REPLACE STREAM FRAUD_SALES_ALERT_STREAM
ON DYNAMIC TABLE FLAT_FRAUD_SALES_ALERT;

SHOW STREAMS;

SELECT COUNT(*) FROM USER_STREAM;
SELECT COUNT(*) FROM CUSTOMER_STREAM;
SELECT COUNT(*) FROM PRODUCT_STREAM;
SELECT COUNT(*) FROM SALES_TRANSACTION_STREAM;
SELECT COUNT(*) FROM FRAUD_SALES_ALERT_STREAM;