--SET CONTEXT
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA RETAIL_CORE;


--CREATE CORE TABLES
CREATE OR REPLACE TABLE CORE_USERS
LIKE RETAIL_RAW.RAW_USERS;

CREATE OR REPLACE TABLE CORE_CUSTOMERS
LIKE RETAIL_RAW.RAW_CUSTOMERS;

CREATE OR REPLACE TABLE CORE_PRODUCTS
LIKE RETAIL_RAW.RAW_PRODUCTS;

CREATE OR REPLACE TABLE CORE_SALES_TRANSACTIONS
LIKE RETAIL_RAW.RAW_SALES_TRANSACTIONS;

CREATE OR REPLACE TABLE CORE_FRAUD_SALES_ALERT
LIKE RETAIL_RAW.FLAT_FRAUD_SALES_ALERT;

SHOW TABLES;

--create tasks for raw to core
CREATE OR REPLACE TASK RAW_TO_CORE
WAREHOUSE = RETAIL_WH
SCHEDULE = '1 MINUTE'
AS
BEGIN

    INSERT INTO CORE_USERS
    SELECT
        ID,
        NAME,
        EMAIL,
        ROLE,
        CREATED_AT
    FROM RETAIL_RAW.USER_STREAM
    WHERE ID IS NOT NULL;

    INSERT INTO CORE_CUSTOMERS
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        EMAIL,
        CITY,
        STATE,
        CUSTOMER_TYPE
    FROM RETAIL_RAW.CUSTOMER_STREAM
    WHERE CUSTOMER_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EMAIL ORDER BY CUSTOMER_ID) = 1;

    INSERT INTO CORE_PRODUCTS
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        BRAND,
        UNIT_PRICE,
        STOCK_QUANTITY
    FROM RETAIL_RAW.PRODUCT_STREAM
    WHERE STOCK_QUANTITY >= 0 AND PRODUCT_ID IS NOT NULL;

    INSERT INTO CORE_SALES_TRANSACTIONS
    SELECT
        TRANSACTION_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        QUANTITY,
        SALES_AMOUNT,
        DISCOUNT_AMOUNT,
        PROFIT_AMOUNT,
        TRANSACTION_DATE,
        PAYMENT_MODE,
        BRANCH_LOCATION
    FROM RETAIL_RAW.SALES_TRANSACTION_STREAM
    WHERE SALES_AMOUNT > 0
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY TRANSACTION_DATE DESC) = 1;

    INSERT INTO CORE_FRAUD_SALES_ALERT
    SELECT
        ID,
        TRANSACTION_ID,
        REASON,
        FRAUD_SCORE,
        STATUS
    FROM RETAIL_RAW.FRAUD_SALES_ALERT_STREAM
    WHERE STATUS = 'PENDING' AND ID IS NOT NULL;

END;

SHOW TASKS;

ALTER TASK RAW_TO_CORE SUSPEND;

SELECT * FROM CORE_USERS;
SELECT * FROM CORE_CUSTOMERS;
SELECT * FROM CORE_PRODUCTS;
SELECT * FROM CORE_SALES_TRANSACTIONS;
SELECT * FROM CORE_FRAUD_SALES_ALERT;

