--Set Context
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA RETAIL_MART;

--Creating Dimension Tables
CREATE OR REPLACE DYNAMIC TABLE DIM_CUSTOMER
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    CITY,
    STATE,
    CUSTOMER_TYPE
FROM RETAIL_CORE.CORE_CUSTOMERS;

CREATE OR REPLACE DYNAMIC TABLE DIM_PRODUCT
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    UNIT_PRICE,
    STOCK_QUANTITY
FROM RETAIL_CORE.CORE_PRODUCTS;

CREATE OR REPLACE DYNAMIC TABLE DIM_BRANCH
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT DISTINCT
    BRANCH_LOCATION AS BRANCH_LOCATION
FROM RETAIL_CORE.CORE_SALES_TRANSACTIONS;

CREATE OR REPLACE DYNAMIC TABLE DIM_DATE
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT DISTINCT
    TRANSACTION_DATE AS DATE,
    YEAR(TRANSACTION_DATE) AS YEAR,
    MONTH(TRANSACTION_DATE) AS MONTH,
    DAY(TRANSACTION_DATE) AS DAY,
    DAYNAME(TRANSACTION_DATE) AS DAY_NAME
FROM RETAIL_CORE.CORE_SALES_TRANSACTIONS;


-- creating fact table
CREATE OR REPLACE DYNAMIC TABLE FACT_SALES
TARGET_LAG = '1 MINUTE'
WAREHOUSE = RETAIL_WH
AS
SELECT
    S.TRANSACTION_ID,
    C.CUSTOMER_ID,
    P.PRODUCT_ID,
    B.BRANCH_LOCATION,
    D.DATE,
    S.QUANTITY,
    S.SALES_AMOUNT,
    S.DISCOUNT_AMOUNT,
    S.PROFIT_AMOUNT,
    S.PAYMENT_MODE
FROM RETAIL_CORE.CORE_SALES_TRANSACTIONS S

LEFT JOIN DIM_CUSTOMER C
ON S.CUSTOMER_ID = C.CUSTOMER_ID

LEFT JOIN DIM_PRODUCT P
ON S.PRODUCT_ID = P.PRODUCT_ID

LEFT JOIN DIM_BRANCH B
ON S.BRANCH_LOCATION = B.BRANCH_LOCATION

LEFT JOIN DIM_DATE D
ON S.TRANSACTION_DATE = D.DATE;


--create Views
CREATE OR REPLACE VIEW VW_TOTAL_SALES
AS
SELECT
    DATE,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(PROFIT_AMOUNT) AS TOTAL_PROFIT
FROM FACT_SALES
GROUP BY DATE;

CREATE OR REPLACE VIEW VW_TOP_PRODUCTS
AS
SELECT
    PRODUCT_ID,
    SUM(SALES_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES
GROUP BY PRODUCT_ID
ORDER BY TOTAL_REVENUE DESC;

CREATE OR REPLACE VIEW VW_FRAUD_TRANSACTIONS
AS
SELECT
    TRANSACTION_ID,
    REASON,
    FRAUD_SCORE,
    STATUS
FROM RETAIL_CORE.CORE_FRAUD_SALES_ALERT
WHERE STATUS = 'PENDING';

--create Materialized Views
CREATE OR REPLACE MATERIALIZED VIEW MV_MONTHLY_REVENUE
AS
SELECT
    YEAR(TRANSACTION_DATE) AS YEAR,
    MONTH(TRANSACTION_DATE) AS MONTH,
    SUM(SALES_AMOUNT) AS MONTHLY_REVENUE
FROM RETAIL_CORE.CORE_SALES_TRANSACTIONS
GROUP BY YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE);

