--set context
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;

--create roles
CREATE OR REPLACE ROLE DATA_ANALYST;
CREATE OR REPLACE ROLE BUSINESS_MANAGER;

--grant permissions to roles
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_MART TO ROLE DATA_ANALYST;

GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE BUSINESS_MANAGER;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE BUSINESS_MANAGER;
GRANT USAGE ON SCHEMA RETAIL_MART TO ROLE BUSINESS_MANAGER;

GRANT SELECT ON TABLE RETAIL_MART.DIM_CUSTOMER TO ROLE DATA_ANALYST;
GRANT SELECT ON TABLE RETAIL_MART.DIM_PRODUCT TO ROLE DATA_ANALYST;
GRANT SELECT ON TABLE RETAIL_MART.DIM_BRANCH TO ROLE DATA_ANALYST;
GRANT SELECT ON TABLE RETAIL_MART.DIM_DATE TO ROLE DATA_ANALYST;
GRANT SELECT ON TABLE RETAIL_MART.FACT_SALES TO ROLE DATA_ANALYST;

GRANT SELECT ON TABLE RETAIL_MART.DIM_CUSTOMER TO ROLE BUSINESS_MANAGER;
GRANT SELECT ON TABLE RETAIL_MART.DIM_PRODUCT TO ROLE BUSINESS_MANAGER;
GRANT SELECT ON TABLE RETAIL_MART.DIM_BRANCH TO ROLE BUSINESS_MANAGER;
GRANT SELECT ON TABLE RETAIL_MART.DIM_DATE TO ROLE BUSINESS_MANAGER;
GRANT SELECT ON TABLE RETAIL_MART.FACT_SALES TO ROLE BUSINESS_MANAGER;

GRANT ROLE DATA_ANALYST TO USER DERELJASPER29;
GRANT ROLE BUSINESS_MANAGER TO USER DERELJASPER29;

SHOW USERS;

SHOW ROLES;

SHOW GRANTS TO USER DERELJASPER29;

--Time Travel Recovery
CREATE OR REPLACE TABLE FACT_SALES_RECOVERY
AS
SELECT *
FROM FACT_SALES
AT (OFFSET => -60*5);

--Zero Copy Cloning
CREATE OR REPLACE SCHEMA RETAIL_MART_RECOVERY
CLONE RETAIL_MART;

--Masking Policy
CREATE OR REPLACE MASKING POLICY EMAIL_MASK_POLICY
AS (VAL STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN')
    THEN VAL
    WHEN CURRENT_ROLE() = 'DATA_ANALYST'
    THEN CONCAT('XXXXXX', RIGHT(VAL, 8))
    ELSE '********'
END;